# Multi-Site Study

::: {.instr_box

If this is a multi-site study (i.e., a study in which two or more institutions coordinate, with each institution completing all research activities outlined in a specific protocol) and the Penn State PI is the lead investigator, describe the processes to ensure communication among sites in the sections below.

:::

> [Do not type here]

## Other sites

::: {.instr_box}

List the name and location of all other participating sites. Provide
the name, qualifications and contact information for the principal
investigator at each site and indicate which IRB will be reviewing the
study at each site.

:::

> [Type protocol text here or indicate as not applicable]

## Communication Plans

::: {.instr_box}

Describe the plan for regular communication between the overall study
director and the other sites to ensure that all sites have the most
current version of the protocol, consent document, etc. Describe the
process to ensure all modifications have been communicated to sites.
Describe the process to ensure that all required approvals have been
obtained at each site (including approval by the site's IRB of
record). Describe the process for communication of problems with the
research, interim results, and closure of the study.

:::

> [Type protocol text here or indicate as not applicable]

## Data Submission and Security Plan

::: {.instr_box}

Describe the process and schedule for data submission and provide the
data security plan for data collected from other sites. Describe the
process to ensure all engaged participating sites will safeguard data
as required by local information security policies.

:::

> [Type protocol text here or indicate as not applicable]

## Subject Enrollment

::: {.instr_box}

Describe the procedures for coordination of subject enrollment and
randomization for the overall project.

:::

> [Type protocol text here or indicate as not applicable]

## Reporting of Adverse Events and New Information

::: {.instr_box}

Describe how adverse events and other information will be reported
from the clinical sites to the overall study director. Provide the
timeframe for this reporting.

:::

> [Type protocol text here or indicate as not applicable]

## Audit and Monitoring Plans

::: {.instr_box}

Describe the process to ensure all local site investigators conduct
the study appropriately. Describe any on-site auditing and monitoring
plans for the study.

:::

> [Type protocol text here or indicate as not applicable]
